{
  "type": "record",
  "name": "Transaction",
  "namespace": "com.payment.system",
  "fields": [
    {"name": "transaction_id", "type": "string"},
    {"name": "timestamp", "type": "string"},
    {"name": "channel", "type": "string"},
    {"name": "amount", "type": "double"},
    {"name": "currency", "type": "string"},
    {
      "name": "merchant",
      "type": {
        "type": "record",
        "name": "Merchant",
        "fields": [
          {"name": "id", "type": "string"},
          {"name": "name", "type": "string"},
          {"name": "country", "type": "string"}
        ]
      }
    },
    {
      "name": "payer",
      "type": {
        "type": "record",
        "name": "Payer",
        "fields": [
          {"name": "account_id", "type": "string"},
          {"name": "pan_last", "type": "string"},
          {"name": "ip_address", "type": ["null", "string"], "default": null},
          {"name": "device_id", "type": ["null", "string"], "default": null}
        ]
      }
    }
  ]
}
