# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace      # Removes extra spaces at the end of lines
      - id: end-of-file-fixer        # Ensures files end with a newline
      - id: check-yaml               # Validates your K8s YAML files
      - id: check-added-large-files # Prevents committing huge files by mistake

  - repo: https://github.com/psf/black
    rev: 26.3.1
    hooks:
      - id: black                   # The "uncompromising" Python formatter

  - repo: https://github.com/pycqa/isort
    rev: 9.0.1
    hooks:
      - id: isort                   # Sorts imports alphabetically and by group

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8                  # Checks for PEP8 style violations and bugs
        args: ["--max-line-length=88", "--extend-ignore=E203,W503"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v2.3.0
    hooks:
      - id: mypy                    # Checks for Type Hinting errors (Critical for Senior roles)
